<?php

function satellite_passage_block_info() {
   $blocks = array();
   $blocks['satellite_passage_block'] = array(
      'info' => t('Sentinel Passage'),
   );
   return $blocks;
}

function satellite_passage_block_view($delta='') {
   $block = array();
   switch ($delta) {
      case 'satellite_passage_block':
      $block['content'] = satellite_passage_main_content(); // set the content of the block to our satellite_passage_main_content
      break;
   }
   return $block;
}


function satellite_passage_main_content(){

   $site_name = variable_get('site_name', 'Default');

   $mpath = drupal_get_path('module', 'satellite_passage');
   $ol5_path = libraries_get_path('openlayers5');
   $ol_switcher_path = libraries_get_path('ol-layerswitcher');
   $jq_path = drupal_get_path('module', 'jquery_update');
 
   drupal_add_css($mpath . '/css/satellite_passage_style.css');
   drupal_add_css($ol5_path . '/css/ol.css');
   drupal_add_css($ol_switcher_path . '/scr/ol-layerswitcher.css');
 
   drupal_add_js($ol5_path . '/build/ol.js');
   drupal_add_js($ol_switcher_path . '/build/ol-layerswitcher.js');
   drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4.js', 'external');
   drupal_add_js(array('site_name' => $site_name), 'setting');


    //<link rel="stylesheet" href="/sites/satellittdata.metsis.met.no/libraries/openlayers3/apidoc/styles/bootstrap.min.css">
    //<script src="/sites/all/modules/jquery_update/replace/jquery/1.10/jquery.min.js"></script>
    //<script src="/sites/satellittdata.metsis.met.no/libraries/openlayers3/apidoc/scripts/bootstrap.min.js"></script>

return '
    <div id="map" class="map"></div>
    <div id="info"></div>


    <div class="controls">
        <label>Acquisition Start:</label>
        <input id="boxStart" type="text" value="" class="date"/>
        <input id="timeStart-kml" type="range" min="0" max="100" value="0" />
    </div>

    <div class="controls">
        <label>Acquisition End :</label>
        <input id="boxEnd" type="text" value="" class="date"/>
        <input id="timeEnd-kml" type="range" min="0" max="100" value="100"/>
    </div>

    <script type="text/javascript" src="/'.$mpath.'/js/satellite_passage.js"></script>
';

}
?>
